apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envhub-agent.fullname" . }}
  namespace: {{ include "envhub-agent.namespace" . }}
  labels:
    {{- include "envhub-agent.labels" . | nindent 4 }}
type: Opaque
data:
  enrollment-token: {{ .Values.enrollmentToken | b64enc | quote }}
