{{- if and .Values.selfUpgrade .Values.selfUpgrade.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "envhub-agent.fullname" . }}-self-upgrade
  labels:
    {{- include "envhub-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "envhub-agent.fullname" . }}
    namespace: {{ include "envhub-agent.namespace" . }}
{{- end }}
