{{- $upgradeTokenSecret := (get .Values "upgradeTokenSecret") | default (dict) }}
{{- if (get $upgradeTokenSecret "create") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-upgrade-token" (include "envhub-agent.fullname" .)) (get $upgradeTokenSecret "existingSecret") }}
  namespace: {{ include "envhub-agent.namespace" . }}
  labels:
    {{- include "envhub-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ (get $upgradeTokenSecret "token") | default "" | quote }}
{{- end }}
